FROM docker.***REMOVED***/sles11

ENV http_proxy http://proxy.***REMOVED***:8080
ENV https_proxy http://proxy.***REMOVED***:8080
ENV no_proxy sap.corp,localhost,10.0.2.2
RUN zypper -n install tar && zypper clean
